const { contextBridge, ipcRenderer } = require("electron");

function subscribe(channel, callback) {
  const listener = (_event, ...args) => callback(...args);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld("zevrinDesktop", {
  isDesktop: true,
  platform: process.platform,
  selectFolder: () => ipcRenderer.invoke("zevrin:select-folder"),
  cloneRepository: (repoUrl) => ipcRenderer.invoke("zevrin:clone-repository", repoUrl),
  revealPath: (root, relativePath) => ipcRenderer.invoke("zevrin:reveal-path", root, relativePath),
  openExternal: url => ipcRenderer.invoke("zevrin:open-external", url),
  listFiles: (root, relativePath) => ipcRenderer.invoke("zevrin:list-files", root, relativePath),
  searchFiles: (root, query) => ipcRenderer.invoke("zevrin:search-files", root, query),
  searchText: (root, query, options) => ipcRenderer.invoke("zevrin:search-text", root, query, options),
  readFile: (root, relativePath) => ipcRenderer.invoke("zevrin:read-file", root, relativePath),
  writeFile: (root, relativePath, contents) => ipcRenderer.invoke("zevrin:write-file", root, relativePath, contents),
  gitStatus: root => ipcRenderer.invoke("zevrin:git-status", root),
  gitDiff: (root, file, staged) => ipcRenderer.invoke("zevrin:git-diff", root, file, staged),
  gitFileVersions: (root, file, staged) => ipcRenderer.invoke("zevrin:git-file-versions", root, file, staged),
  gitStage: (root, paths) => ipcRenderer.invoke("zevrin:git-stage", root, paths),
  gitUnstage: (root, paths) => ipcRenderer.invoke("zevrin:git-unstage", root, paths),
  gitDiscard: (root, paths) => ipcRenderer.invoke("zevrin:git-discard", root, paths),
  gitCommit: (root, message) => ipcRenderer.invoke("zevrin:git-commit", root, message),
  gitGenerateMessage: (root, provider) => ipcRenderer.invoke("zevrin:git-generate-message", root, provider),
  gitInit: root => ipcRenderer.invoke("zevrin:git-init", root),
  gitBranches: root => ipcRenderer.invoke("zevrin:git-branches", root),
  gitCheckout: (root, branch, create) => ipcRenderer.invoke("zevrin:git-checkout", root, branch, create === true),
  gitLog: root => ipcRenderer.invoke("zevrin:git-log", root),
  gitFetch: root => ipcRenderer.invoke("zevrin:git-fetch", root),
  gitPull: root => ipcRenderer.invoke("zevrin:git-pull", root),
  gitPush: root => ipcRenderer.invoke("zevrin:git-push", root),
  gitWorktrees: root => ipcRenderer.invoke("zevrin:git-worktrees", root),
  gitWorktreeCreate: (root, branch) => ipcRenderer.invoke("zevrin:git-worktree-create", root, branch),
  gitWorktreeRemove: (root, worktreePath, force) => ipcRenderer.invoke("zevrin:git-worktree-remove", root, worktreePath, force === true),
  gitWorktreeSummary: (root, worktreePath, branch) => ipcRenderer.invoke("zevrin:git-worktree-summary", root, worktreePath, branch),
  gitBranchChanges: (root, branch, worktreePath) => ipcRenderer.invoke("zevrin:git-branch-changes", root, branch, worktreePath),
  gitBranchFile: (root, branch, file, worktreePath, uncommitted) => ipcRenderer.invoke("zevrin:git-branch-file", root, branch, file, worktreePath, uncommitted === true),
  gitWorktreeFinish: (root, worktreePath, branch, mode) => ipcRenderer.invoke("zevrin:git-worktree-finish", root, worktreePath, branch, mode),
  agentStart: (id, root, options) => ipcRenderer.invoke("zevrin:agent-start", id, root, options || {}),
  agentSend: (id, text) => ipcRenderer.invoke("zevrin:agent-send", id, text),
  agentRespond: (id, requestId, decision) => ipcRenderer.invoke("zevrin:agent-respond", id, requestId, decision),
  agentInterrupt: id => ipcRenderer.invoke("zevrin:agent-interrupt", id),
  agentSetMode: (id, mode) => ipcRenderer.invoke("zevrin:agent-set-mode", id, mode),
  agentStop: id => ipcRenderer.invoke("zevrin:agent-stop", id),
  agentSetModel: (id, model) => ipcRenderer.invoke("zevrin:agent-set-model", id, model),
  agentSessions: root => ipcRenderer.invoke("zevrin:agent-sessions", root),
  agentHistory: (root, sessionId) => ipcRenderer.invoke("zevrin:agent-history", root, sessionId),
  mcpInfo: () => ipcRenderer.invoke("zevrin:mcp-info"),
  vscodeStatus: () => ipcRenderer.invoke("zevrin:vscode-status"),
  vscodeSetup: agent => ipcRenderer.invoke("zevrin:vscode-setup", agent),
  vscodeUrl: (root, agent, instance) => ipcRenderer.invoke("zevrin:vscode-url", root, agent, instance),
  vscodeCommand: (root, agent, action, instance) => ipcRenderer.invoke("zevrin:vscode-command", root, agent, action, instance),
  vscodeDiagnose: (root, agent, instance) => ipcRenderer.invoke("zevrin:vscode-diagnose", root, agent, instance),
  vscodeInstallVsix: agent => ipcRenderer.invoke("zevrin:vscode-install-vsix", agent),
  vscodeRestart: () => ipcRenderer.invoke("zevrin:vscode-restart"),
  codexStart: (id, root, options) => ipcRenderer.invoke("zevrin:codex-start", id, root, options),
  codexSend: (id, text, images) => ipcRenderer.invoke("zevrin:codex-send", id, text, images),
  codexInterrupt: id => ipcRenderer.invoke("zevrin:codex-interrupt", id),
  codexConfigure: (id, changes) => ipcRenderer.invoke("zevrin:codex-configure", id, changes),
  codexStop: id => ipcRenderer.invoke("zevrin:codex-stop", id),
  codexThreads: root => ipcRenderer.invoke("zevrin:codex-threads", root),
  codexThreadMessages: (root, threadId) => ipcRenderer.invoke("zevrin:codex-thread-messages", root, threadId),
  onCodexEvent: callback => subscribe("zevrin:codex-event", callback),
  onVscodeProgress: callback => subscribe("zevrin:vscode-progress", callback),
  onAppCommand: callback => subscribe("zevrin:app-command", callback),
  appCommandResult: (requestId, result, error) => ipcRenderer.invoke("zevrin:app-command-result", requestId, result, error),
  onAgentEvent: callback => subscribe("zevrin:agent-event", callback),
  aiTools: () => ipcRenderer.invoke("zevrin:ai-tools"),
  launchAI: (root, id, terminalId) => ipcRenderer.invoke("zevrin:ai-launch", root, id, terminalId),
  createTerminal: root => ipcRenderer.invoke("zevrin:terminal-create", root),
  writeTerminal: (id, data) => ipcRenderer.send("zevrin:terminal-write", id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send("zevrin:terminal-resize", id, cols, rows),
  closeTerminal: id => ipcRenderer.send("zevrin:terminal-close", id),
  onTerminalData: callback => subscribe("zevrin:terminal-data", callback),
  onTerminalExit: callback => subscribe("zevrin:terminal-exit", callback),
  onToggleCommandCenter: callback => subscribe("zevrin:toggle-command-center", callback),
  onToggleFlowMode: callback => subscribe("zevrin:toggle-flow-mode", callback),
  setFlowMode: enabled => ipcRenderer.invoke("zevrin:set-flow-mode", Boolean(enabled)),
  previewCapture: id => ipcRenderer.invoke("zevrin:preview-capture", id),
  previewEval: (id, script) => ipcRenderer.invoke("zevrin:preview-eval", id, script),
  previewDevtools: id => ipcRenderer.invoke("zevrin:preview-devtools", id),
  previewAttach: id => ipcRenderer.invoke("zevrin:preview-attach", id),
  previewNetwork: id => ipcRenderer.invoke("zevrin:preview-network", id),
  previewRecordStart: id => ipcRenderer.invoke("zevrin:preview-record-start", id),
  previewRecordStop: id => ipcRenderer.invoke("zevrin:preview-record-stop", id),
  previewInput: (id, input) => ipcRenderer.invoke("zevrin:preview-input", id, input),
  saveArtifact: (root, name, base64, text) => ipcRenderer.invoke("zevrin:save-artifact", root, name, base64, text),
  mcpConnectClaude: () => ipcRenderer.invoke("zevrin:mcp-connect-claude"),
  devicesList: () => ipcRenderer.invoke("zevrin:devices-list"),
  deviceBoot: (platform, id) => ipcRenderer.invoke("zevrin:device-boot", platform, id),
  deviceShutdown: (platform, id, serial) => ipcRenderer.invoke("zevrin:device-shutdown", platform, id, serial),
  deviceFocus: platform => ipcRenderer.invoke("zevrin:device-focus", platform),
  deviceScreenshot: (platform, id, serial) => ipcRenderer.invoke("zevrin:device-screenshot", platform, id, serial),
  deviceOpenUrl: (platform, id, serial, url) => ipcRenderer.invoke("zevrin:device-open-url", platform, id, serial, url),
  deviceInstall: (platform, id, serial) => ipcRenderer.invoke("zevrin:device-install", platform, id, serial),
  deviceInput: (platform, id, serial, input) => ipcRenderer.invoke("zevrin:device-input", platform, id, serial, input),
  deviceMirrorStart: (platform, id, serial, fps) => ipcRenderer.invoke("zevrin:device-mirror-start", platform, id, serial, fps),
  inlineEdit: (id, root, request) => ipcRenderer.invoke("zevrin:inline-edit", id, root, request),
  inlineEditCancel: id => ipcRenderer.invoke("zevrin:inline-edit-cancel", id),
  checkpointCreate: (root, label) => ipcRenderer.invoke("zevrin:checkpoint-create", root, label),
  checkpointChanges: (root, id) => ipcRenderer.invoke("zevrin:checkpoint-changes", root, id),
  checkpointRevertHunk: (root, id, file, index) => ipcRenderer.invoke("zevrin:checkpoint-revert-hunk", root, id, file, index),
  checkpointRevertFile: (root, id, file) => ipcRenderer.invoke("zevrin:checkpoint-revert-file", root, id, file),
  checkpointRestore: (root, id) => ipcRenderer.invoke("zevrin:checkpoint-restore", root, id),
  deviceLogs: (platform, id, serial, options) => ipcRenderer.invoke("zevrin:device-logs", platform, id, serial, options),
  deviceAppearance: (platform, id, serial, mode) => ipcRenderer.invoke("zevrin:device-appearance", platform, id, serial, mode),
  deviceRecordStart: (platform, id, serial) => ipcRenderer.invoke("zevrin:device-record-start", platform, id, serial),
  deviceRecordStop: (platform, id) => ipcRenderer.invoke("zevrin:device-record-stop", platform, id),
  deviceRevealRecording: file => ipcRenderer.invoke("zevrin:device-reveal-recording", file),
  deviceStreamStart: (platform, id, serial) => ipcRenderer.invoke("zevrin:device-stream-start", platform, id, serial),
  deviceStreamStop: (platform, id) => ipcRenderer.invoke("zevrin:device-stream-stop", platform, id),
  onDeviceStreamData: callback => subscribe("zevrin:device-stream-data", callback),
  onDeviceStreamError: callback => subscribe("zevrin:device-stream-error", callback),
  openScreenRecordingSettings: () => ipcRenderer.invoke("zevrin:open-screen-recording-settings"),
  deviceMirrorStop: (platform, id) => ipcRenderer.invoke("zevrin:device-mirror-stop", platform, id),
  onDeviceFrame: callback => subscribe("zevrin:device-frame", callback),
  onDeviceFrameError: callback => subscribe("zevrin:device-frame-error", callback),
  deviceWindowSource: (platform, name, id, serial) => ipcRenderer.invoke("zevrin:device-window-source", platform, name, id, serial),
  deviceWindowInput: (platform, name, input) => ipcRenderer.invoke("zevrin:device-window-input", platform, name, input),
  onOpenFolder: callback => subscribe("zevrin:open-folder", callback),
});
