export type GitChange = { path: string; from: string | null; index: string; worktree: string };
export type GitStatus = { isRepo: boolean; branch: string | null; upstream: string | null; ahead: number; behind: number; unborn: boolean; changes: GitChange[] };
export type GitWorktree = { path: string; branch: string | null; detached: boolean; bare: boolean; locked: boolean; prunable: boolean; current: boolean };
export type GitBranch = { name: string; current: boolean; upstream: string | null };
export type GitCommit = { hash: string; short: string; subject: string; author: string; date: string };
export type FileMatch = { path: string; name: string };
export type NetworkEntry = { url: string; method: string; status: number | null; type: string | null; failed: boolean; error: string | null; ms: number | null; size: number | null };
export type PreviewInput = { type: "click"; x: number; y: number } | { type: "type"; text: string } | { type: "key"; key: string } | { type: "scroll"; x?: number; y?: number; deltaX?: number; deltaY?: number };
export type DevicePlatform = "ios" | "android";
export type DeviceInfo = { platform: DevicePlatform; id: string; name: string; runtime: string; state: "booted" | "shutdown" | "booting" | string; serial?: string | null; kind: "phone" | "tablet" | "watch" | "tv" };
export type DeviceSupport = { ios: boolean; iosReason: string; android: boolean; androidReason: string; adb: boolean; sdkRoot: string | null; idb?: boolean };
export type DeviceInput = { type: "tap"; x: number; y: number } | { type: "swipe"; x1: number; y1: number; x2: number; y2: number; duration?: number } | { type: "text"; text: string } | { type: "key"; key: string };
export type DevicesList = { support: DeviceSupport; devices: DeviceInfo[]; errors: string[] };
export type TextMatch = { path: string; line: number; column: number; text: string; preview: string };
export type TextSearchResult = { matches: TextMatch[]; truncated: boolean; filesSearched: number };
export type AIToolId = "claude" | "gemini" | "codex" | "opencode";
export type AIToolInfo = { id: AIToolId; name: string; available: boolean };
export type AgentPermissionMode = "default" | "acceptEdits" | "plan" | "bypassPermissions" | "dontAsk" | "auto";
export type AgentEffort = "low" | "medium" | "high" | "xhigh" | "max";
export type AgentStartOptions = { permissionMode?: AgentPermissionMode; resume?: string; model?: string; effort?: AgentEffort };
export type AgentModelInfo = { value: string; displayName: string; description: string; supportsEffort?: boolean };
export type AgentCommandInfo = { name: string; description: string; argumentHint: string };
export type AgentAccountInfo = { email?: string; organization?: string; subscriptionType?: string; apiProvider?: string };
export type AgentMcpStatus = { name: string; status: string; error?: string };
export type AgentSessionInfo = { sessionId: string; summary: string; lastModified: number };
export type AgentMessageContent = string | Array<{ type: "text"; text: string } | { type: "image"; source: { type: "base64"; media_type: string; data: string } }>;
export type ExtensionAgentId = "claude" | "codex" | "gemini";
export type ExtensionAgentStatus = { label: string; extensionId: string; cli: string; installed: boolean; source: string | null; version?: string | null; runnable?: boolean; reason?: string; viewContainerId?: string | null };
export type VscodeStatus = { agents: Record<ExtensionAgentId, ExtensionAgentStatus>; supported: boolean; platform: string; serverVersion: string; serverInstalled: boolean; extensionInstalled: boolean; extensionSource: string | null; running: boolean; url: string | null; busy: boolean; error: string | null };
export type VscodeProgress = { step: "download" | "extract" | "extension" | "start" | "ready" | "error"; message: string; fraction: number | null };
export type InlineEditRequest = { path: string; language?: string; before: string; selection: string; after: string; instruction: string; model?: string };
export type CheckpointHunk = { header: string; oldStart: number; newStart: number; context: string; lines: string[] };
export type CheckpointFileChange = { path: string; status: "modified" | "added" | "deleted"; binary: boolean; additions: number; deletions: number; hunks: CheckpointHunk[] };
export type AppCommandName = "list_workspaces" | "get_workspace_state" | "open_file" | "show_preview" | "add_canvas_note" | "get_canvas" | "open_tile" | "close_tile" | "apply_layout" | "run_in_terminal" | "notify" | "get_preview_page" | "preview_screenshot" | "get_preview_console" | "run_in_preview" | "preview_navigate" | "preview_snapshot" | "preview_click" | "preview_type" | "preview_press_key" | "preview_scroll" | "preview_wait_for" | "preview_network" | "preview_record" | "list_devices" | "boot_device" | "device_screenshot" | "open_url_on_device" | "device_logs" | "set_device_appearance";
export type AgentBridgeEvent =
  | { type: "started" }
  | { type: "message"; message: Record<string, unknown> }
  | { type: "permission"; requestId: string; toolName: string; input: Record<string, unknown>; suggestions?: unknown[] }
  | { type: "permission_resolved"; requestId: string }
  | { type: "info"; models: AgentModelInfo[]; commands: AgentCommandInfo[]; account: AgentAccountInfo; mcp: AgentMcpStatus[]; effort: AgentEffort | null }
  | { type: "error"; message: string }
  | { type: "closed"; reason?: string };

declare global {
  interface Window {
    zevrinDesktop?: {
      isDesktop: boolean;
      platform: string;
      selectFolder: () => Promise<string | null>;
      cloneRepository: (repoUrl: string) => Promise<{ success: boolean; path?: string; error?: string }>;
      revealPath: (root: string, relativePath?: string) => Promise<boolean>;
      openExternal: (url: string) => Promise<boolean>;
      listFiles: (root: string, relativePath?: string) => Promise<Array<{ name: string; path: string; directory: boolean }>>;
      searchFiles: (root: string, query: string) => Promise<FileMatch[]>;
      searchText: (root: string, query: string, options?: { caseSensitive?: boolean }) => Promise<TextSearchResult>;
      readFile: (root: string, relativePath: string) => Promise<string>;
      writeFile: (root: string, relativePath: string, contents: string) => Promise<boolean>;
      gitStatus: (root: string) => Promise<GitStatus>;
      gitDiff: (root: string, file: string, staged: boolean) => Promise<string>;
      gitFileVersions: (root: string, file: string, staged: boolean) => Promise<{ original: string; modified: string }>;
      gitStage: (root: string, paths: string[]) => Promise<boolean>;
      gitUnstage: (root: string, paths: string[]) => Promise<boolean>;
      gitDiscard: (root: string, paths: string[]) => Promise<boolean>;
      gitCommit: (root: string, message: string) => Promise<boolean>;
      gitInit: (root: string) => Promise<boolean>;
      gitBranches: (root: string) => Promise<GitBranch[]>;
      gitCheckout: (root: string, branch: string, create?: boolean) => Promise<boolean>;
      gitLog: (root: string) => Promise<GitCommit[]>;
      gitFetch: (root: string) => Promise<boolean>;
      gitPull: (root: string) => Promise<boolean>;
      gitPush: (root: string) => Promise<boolean>;
      gitWorktrees: (root: string) => Promise<GitWorktree[]>;
      gitWorktreeCreate: (root: string, branch: string) => Promise<{ path: string; branch: string }>;
      gitWorktreeRemove: (root: string, worktreePath: string, force?: boolean) => Promise<boolean>;
      gitWorktreeSummary: (root: string, worktreePath: string, branch: string) => Promise<{ dirty: number; ahead: number; stat: string; target: string }>;
      gitBranchChanges: (root: string, branch: string, worktreePath?: string | null) => Promise<Array<{ status: string; path: string; uncommitted: boolean }>>;
      gitBranchFile: (root: string, branch: string, file: string, worktreePath?: string | null, uncommitted?: boolean) => Promise<{ original: string; modified: string }>;
      gitWorktreeFinish: (root: string, worktreePath: string, branch: string, mode: "merge" | "remove" | "discard") => Promise<boolean>;
      agentStart: (id: string, root: string, options?: AgentStartOptions) => Promise<boolean>;
      agentSend: (id: string, content: AgentMessageContent) => Promise<boolean>;
      agentRespond: (id: string, requestId: string, decision: "allow" | "allow_always" | "deny") => Promise<boolean>;
      agentInterrupt: (id: string) => Promise<boolean>;
      agentSetMode: (id: string, mode: AgentPermissionMode) => Promise<boolean>;
      agentStop: (id: string) => Promise<boolean>;
      agentSetModel: (id: string, model: string | null) => Promise<boolean>;
      agentSessions: (root: string) => Promise<AgentSessionInfo[]>;
      agentHistory: (root: string, sessionId: string) => Promise<Array<Record<string, unknown>>>;
      mcpInfo: () => Promise<{ url: string; command: string; token: string } | null>;
      vscodeStatus: () => Promise<VscodeStatus>;
      vscodeSetup: (agent?: ExtensionAgentId) => Promise<VscodeStatus>;
      vscodeUrl: (root: string, agent?: ExtensionAgentId, instance?: string) => Promise<string | null>;
      vscodeCommand: (root: string, agent: ExtensionAgentId, action: "open" | "chatOnly" | "widen" | "closeEditors" | "diagnose", instance?: string) => Promise<boolean>;
      vscodeDiagnose: (root: string, agent: ExtensionAgentId, instance?: string) => Promise<{ answered: boolean; report: unknown; serverLog: string | null }>;
      vscodeInstallVsix: (agent?: ExtensionAgentId) => Promise<VscodeStatus | null>;
      vscodeRestart: () => Promise<VscodeStatus>;
      codexStart: (id: string, root: string, options: { threadId?: string | null; mode?: "chat" | "agent" | "full"; model?: string | null; effort?: string | null }) => Promise<{ threadId: string | null; codexPath: string }>;
      codexSend: (id: string, text: string, images: Array<{ mediaType: string; data: string }>) => Promise<boolean>;
      codexInterrupt: (id: string) => Promise<boolean>;
      codexConfigure: (id: string, changes: { mode?: "chat" | "agent" | "full"; model?: string | null; effort?: string | null; threadId?: string | null }) => Promise<boolean>;
      codexStop: (id: string) => Promise<boolean>;
      codexThreads: (root: string) => Promise<Array<{ threadId: string; summary: string; lastModified: number }>>;
      codexThreadMessages: (root: string, threadId: string) => Promise<Array<{ role: string; text: string }>>;
      onCodexEvent: (callback: (id: string, event: { type: string; [key: string]: unknown }) => void) => () => void;
      onVscodeProgress: (callback: (event: VscodeProgress) => void) => () => void;
      onAppCommand: (callback: (requestId: string, command: AppCommandName, args: Record<string, unknown>, workspace: string | null) => void) => () => void;
      appCommandResult: (requestId: string, result: unknown, error?: string) => Promise<boolean>;
      onAgentEvent: (callback: (id: string, event: AgentBridgeEvent) => void) => () => void;
      aiTools: () => Promise<AIToolInfo[]>;
      launchAI: (root: string, id: AIToolId, terminalId: string) => Promise<boolean>;
      createTerminal: (root: string) => Promise<string>;
      writeTerminal: (id: string, data: string) => void;
      resizeTerminal: (id: string, cols: number, rows: number) => void;
      closeTerminal: (id: string) => void;
      onTerminalData: (callback: (id: string, data: string) => void) => () => void;
      onTerminalExit: (callback: (id: string, exitCode: number) => void) => () => void;
      onToggleCommandCenter: (callback: () => void) => () => void;
      onToggleFlowMode: (callback: () => void) => () => void;
      setFlowMode: (enabled: boolean) => Promise<boolean>;
      previewCapture: (id: number) => Promise<{ mimeType: string; data: string; width: number; height: number }>;
      previewEval: (id: number, script: string) => Promise<unknown>;
      previewDevtools: (id: number) => Promise<boolean>;
      previewAttach: (id: number) => Promise<boolean>;
      previewNetwork: (id: number) => Promise<NetworkEntry[]>;
      previewRecordStart: (id: number) => Promise<boolean>;
      previewRecordStop: (id: number) => Promise<{ frames: Array<{ data: string; t: number }>; durationMs: number; network: NetworkEntry[] }>;
      previewInput: (id: number, input: PreviewInput) => Promise<boolean>;
      saveArtifact: (root: string, name: string, base64: string | null, text?: string) => Promise<{ path: string; relative: string }>;
      mcpConnectClaude: () => Promise<boolean>;
      devicesList: () => Promise<DevicesList>;
      deviceBoot: (platform: DevicePlatform, id: string) => Promise<boolean>;
      deviceShutdown: (platform: DevicePlatform, id: string, serial?: string | null) => Promise<boolean>;
      deviceFocus: (platform: DevicePlatform) => Promise<boolean>;
      deviceScreenshot: (platform: DevicePlatform, id: string, serial?: string | null) => Promise<{ mimeType: string; data: string }>;
      deviceOpenUrl: (platform: DevicePlatform, id: string, serial: string | null | undefined, url: string) => Promise<boolean>;
      deviceInstall: (platform: DevicePlatform, id: string, serial?: string | null) => Promise<string | null>;
      deviceInput: (platform: DevicePlatform, id: string, serial: string | null | undefined, input: DeviceInput) => Promise<boolean>;
      deviceMirrorStart: (platform: DevicePlatform, id: string, serial: string | null | undefined, fps: number) => Promise<boolean>;
      inlineEdit: (id: string, root: string, request: InlineEditRequest) => Promise<{ code: string }>;
      inlineEditCancel: (id: string) => Promise<boolean>;
      checkpointCreate: (root: string, label?: string) => Promise<{ id: string; tree: string; at: number }>;
      checkpointChanges: (root: string, id: string) => Promise<CheckpointFileChange[]>;
      checkpointRevertHunk: (root: string, id: string, file: string, index: number) => Promise<boolean>;
      checkpointRevertFile: (root: string, id: string, file: string) => Promise<boolean>;
      checkpointRestore: (root: string, id: string) => Promise<number>;
      deviceLogs: (platform: DevicePlatform, id: string, serial: string | null | undefined, options?: { minutes?: number; errorsOnly?: boolean; filter?: string; lines?: number }) => Promise<string>;
      deviceAppearance: (platform: DevicePlatform, id: string, serial: string | null | undefined, mode?: "dark" | "light" | null) => Promise<string>;
      deviceRecordStart: (platform: DevicePlatform, id: string, serial: string | null | undefined) => Promise<{ file: string; startedAt: number }>;
      deviceRecordStop: (platform: DevicePlatform, id: string) => Promise<{ file: string; seconds: number }>;
      deviceRevealRecording: (file: string) => Promise<boolean>;
      deviceStreamStart: (platform: DevicePlatform, id: string, serial: string | null | undefined) => Promise<boolean>;
      deviceStreamStop: (platform: DevicePlatform, id: string) => Promise<boolean>;
      onDeviceStreamData: (callback: (platform: DevicePlatform, id: string, chunk: Uint8Array) => void) => () => void;
      onDeviceStreamError: (callback: (platform: DevicePlatform, id: string, message: string) => void) => () => void;
      openScreenRecordingSettings: () => Promise<boolean>;
      deviceMirrorStop: (platform: DevicePlatform, id: string) => Promise<boolean>;
      onDeviceFrame: (callback: (platform: DevicePlatform, id: string, frame: { mimeType: string; data: string; at: number; ms: number }) => void) => () => void;
      onDeviceFrameError: (callback: (platform: DevicePlatform, id: string, message: string) => void) => () => void;
      deviceWindowSource: (platform: DeviceInfo["platform"], name: string, id: string, serial: string | null) => Promise<{ id: string | null; name: string | null; permission: string }>;
      deviceWindowInput: (platform: DeviceInfo["platform"], name: string, input: DeviceInput) => Promise<boolean>;
      onOpenFolder: (callback: () => void) => () => void;
    };
  }
}
